### PR TITLE
Simple script to handle default routing

### PR DESCRIPTION
**Pull request by wzyboy**
I wrote a simple script to help adding default routing for GoVPN. Users could invoke this script to route all traffic through GoVPN with less typing.

### CODE REVIEW

**Comment by stargrave** [comment]
I have made several trivial commits for your one in addroute-script branch: https://github.com/stargrave/govpn/commits/addroute-script

Are those changes all right?

**Comment by stargrave** [comment]
I think that it will be useful to setup some environment variables like remote gateway's address and predefined TAP interface name when calling those shell scripts. How do you think? I can add them on the next week.

**Comment by wzyboy** [comment]
It would be nice if GoVPN could pass these environment virables when invoking `-up` and `-down` scripts. An alternative way is to pass positional arguments to scripts, as OpenVPN does. If both could be implemented, then the script could be written with great flexiability. :-)

**Comment by stargrave** [comment]
Now remote peer's address and TAP interface name are passed through environment variables at last.

**Comment by wzyboy** [comment]
Great!

**Pull request closed without merging**
