### PR TITLE
Refactor #2

### PR DESCRIPTION
**Pull request by bclermont**
A long list of changes, highlights:

- add support for Android, OSX and Windows clients
- server is a library now
- improved client as a library
- don't `panic`/`os.Exit` anymore, return errors
- wrap errors to get stacktrace
- should pass golint/govet completely
- server can have a custom provisioning mechanism

### CODE REVIEW

**Comment by bclermont** [comment]
this is not yet ready to be merged, it's just ready for @stargrave initial review

**Comment by bclermont** [comment]
I fixed few things.

@stargrave how should TAP I/O errors should be raised to consumers (server or client)?

**Comment by stargrave** [comment]
I will look on all of these patches more closely later -- hope on weekends. I looked quickly on all of them and I like them. There are many minor fixes required, but just stylistic.

One of the minor fix required everywhere is copyright year lowered from 2017 to 2016.

The only thing I do not like is commit about "defer unlock". Defer (at least in previous Go version) is VERY heavy operation. It always much slower then manual functions explicit calling before exit. Of course I agree that it simplifies code and it becomes more easy to read. But Peer structure is some kind of very concurrent and I think the most intense part of GoVPN at all. It must be as fast as possible. So I explicitly omit defer usage in it -- locks must be release as fast as possible to allow other waiting packets to be processed. Maybe I am wrong and exactly that unlocking is the tiny part of overall packet processing time, but I prefere not to think about it and try to create as fast code (exactly here) as we can. The first aim of GoVPN is simplicity and code readability of course, but performance is also desired  property (if it could be achieved relatively easily).

**Comment by stargrave** [comment]
About TAP I/O errors: I am not 100% sure, that I interpret TAP IO error as something fatal. If it happened -- I think that means something that won't work at all. You have to reconfigure something and restart GoVPN. Client and server must not know anything about those kind of errors on the remote side. I have never met TAP IO errors except I have configured something very badly (for example MTU). Client should exit, I think. Server should drop connection and loudly cry about TAP interface unworkability, in my opinion.

**Comment by bclermont** [comment]
> One of the minor fix required everywhere is copyright year lowered from 2017 to 2016.

fixed it. this is due to my manual merge of my branch that I had been working on in the past few weeks

**Comment by bclermont** [comment]
I also wonder if instead of a `chan` to terminate the server if `govpn/server.Server` and `govpn/client.Client` shouldn't just have a `.Stop()` method. and keep hidden inside the `struct` the channel that stop it.

> The only thing I do not like is commit about "defer unlock". Defer (at least in previous Go version) is VERY heavy operation.

I know that, but upcoming Go 1.8 (in few hours/days) double that speed: 

https://go-review.googlesource.com/#/c/29656/

and 1.9 (I can't find the link, but here is something about that https://github.com/golang/go/issues/14939#issuecomment-252935757
) will reduce performance hit even more.

So, I took a chance here and did the chance to increase readability :)

**Comment by stargrave** [comment]
I began merging your branch, but currently not all commits so far. I found that FreeBSD TAPer was not working (trivial fix): https://github.com/stargrave/govpn/commit/41536f516a6bc1528bb892fb1d1e8d5eaa5d6325

Also today I found another damned Sum misusage: https://github.com/stargrave/govpn/commit/30697303bd8e3a2489627962252928bc125ff472.

**Comment by stargrave** [comment]
By the way, about defers: ok, let they stay. I will benchmark it to see the difference. Of course some degradation is acceptable by the price of better readability.

**Comment by klebed** [comment]
Hello, guys!
Sorry for interferring. There is no 'issues' section in this project, but I wanted to leave some feedback, about feature idea, which somewhat related to refactor/further development.
- Make running daemon able to reload peers while operating. For example if administrator want to change 1 peer identity, or drop it, for any reason, but all other peers should not be affected. The same with tun/tap interfaces, if we bring up a new one with couple of peers, but don't want any downtime for currently active peers. This could be implemented by catching custom signal or something like that.

Regards!

**Comment by stargrave** [comment]
Greetings!

>There is no 'issues' section in this project, but I wanted to leave some feedback, about feature idea, which somewhat related to refactor/further development.

Github is not an official point of GoVPN's development. It is just
Git-mirror, nothing more. That is explicitly stated in README file. I
can not turn off pull requests (Github does not allow that), but I wish to.

I am the author and live in Russian Federation. Github is under US
jurisdiction. So at any time blocks and censorship applying could
happen. Moreover, it is likely that Github will block countries like
Iran and Syria, like Sourceforge did, because of US laws -- so Github
can not be in any case a central place of development.

Moreover many Github's features work only with JavaScript turned on and
that JS code is not free or even open. Moreover they block access to
their Git+SSH through Tor. So it is very unpleasant place. Git *mirror*
exists only because of zero price and my patience to allow JS-code
sometimes.

So, please, leave any feedback in govpn-devel@lists.cypherpunks.ru
mailing list (subscription required, because of huge spam quantity).

>- Make running daemon able to reload peers while operating.

Currently daemon parses YAML configuration file every minute or so and
reloads peers availability. Honestly I have not tested this feature for
a long time, but it should add new peers if they appear in config file
and remove ability to connect from disappeared ones.

But this is very good feature request to forcefully disconnect
disappeared ones. And very good feature to catch HUP signal instead of
cron-like job. I will add it to TODO file and hopefully do that task
soon.

Thanks for the feedback!

**Comment by joeblew99** [comment]
@bclermont  This is really nicely done.

Any chance you can fix the conflicts and commit, so i can try it out ?

**Comment by bclermont** [comment]
Conflicts?

**Comment by stargrave** [comment]
I merged all those changes.

**Comment by stargrave** [comment]
Unofortunately it does not work anymore. I have started server, client, they successfully handshaked, but then:

    ERRO[2017-03-04T10:06:40.389307932+03:00] Can not read interface                        error="read /dev/tap0: file already closed" func="govpn.TAP read sink loop" mtu=1515 name=tap0

message appeared. And when I switched server off, client exited with the fatal error:

    FATA[2017-03-04T10:11:00.396539991+03:00] Fatal error                                   error="govpn/client.Client.tap.Close: invalid argument"

**Comment by bclermont** [comment]
I will look at this soon, sorry I couldn't give support before. Been trying to close the lid on a project.

**Comment by bclermont** [comment]
Which OS that is?

**Comment by bclermont** [comment]
Ah FreeBSD, I will install a VM to try that

It happens client or server side?

**Pull request closed without merging**
